public_key: !!binary |
  LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FR
  OEFNSUlCQ2dLQ0FRRUFxQXEvKzBJdUtDbzNqbTZSMGpLSwp3alZEMlYydkxDUzBLamo0a1FIUmRB
  UGVHK2kxN3k1L3dZQk5mR0pJMWd4UmZERmo4UVdCNjRYbmpSZklyU1l4CkhlbFJMK0ZVTHJaSFUw
  ZTRpMkQyT3l2YmxOLzZhZHg4TWl4WVVJOTJMaWJtNDlyOWViOVFIMjIvdTBGV2pRUnQKcU5QNG0y
  Z3haNzB3UXA2ejJMaDQ3QTNwTTIxK0Y4RzdPUnhEY3lkaTJvT1lDQ01veTNCSlJyQlVMSVVHeDhT
  VApvd1dnY2wxSVFSWXNETFVzRlBGbHNtajFKcmVvRXhNVENOOWl2dmZMWm5xclpucldFNnRWK1Zv
  dE5XMmxCYlZYCmZGMXFIVkJqNWpzZ0FXZlgwQmtnR0huenpQTHRJNjFxbEhTalc1b256NkY3SE5V
  dllWdk1udGJVMExCWDI1UHYKYVFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
secret_key: !!binary |
  LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
  QVNDQktjd2dnU2pBZ0VBQW9JQkFRQ29Dci83UWk0b0tqZU8KYnBIU01vckNOVVBaWGE4c0pMUXFP
  UGlSQWRGMEE5NGI2TFh2TG4vQmdFMThZa2pXREZGOE1XUHhCWUhyaGVlTgpGOGl0SmpFZDZWRXY0
  VlF1dGtkVFI3aUxZUFk3Szl1VTMvcHAzSHd5TEZoUWozWXVKdWJqMnYxNXYxQWZiYis3ClFWYU5C
  RzJvMC9pYmFERm52VEJDbnJQWXVIanNEZWt6Ylg0WHdiczVIRU56SjJMYWc1Z0lJeWpMY0VsR3NG
  UXMKaFFiSHhKT2pCYUJ5WFVoQkZpd010U3dVOFdXeWFQVW10NmdURXhNSTMySys5OHRtZXF0bWV0
  WVRxMVg1V2kwMQpiYVVGdFZkOFhXb2RVR1BtT3lBQlo5ZlFHU0FZZWZQTTh1MGpyV3FVZEtOYm1p
  ZlBvWHNjMVM5aFc4eWUxdFRRCnNGZmJrKzlwQWdNQkFBRUNnZ0VBSW9PR3Q5LzVZL1Y3MEt6RUZZ
  U2MvRk45V29WRDU5Q29FbTMrRzZaZ2N6QWkKSytCSmtkVWVsMHMzWHY4K3ozdmJOcU5jVUJJZUE1
  Wk9ueXVONDRaUEcwSWpFeTc0SDluL1gwc0JTOXMvNTVwVAo4TWxxQU5rd3h3dFZua0pBOXl5MVNv
  SmRnbVo1V2VNc09KVXNaaTFOS3BwUzJ2UjFCVVlWeGZFYnBqMEpWUTRYCkpIZ2toNHJzNGdzZEJ3
  K09FcDN3WVlydUtFTTRmcHB1REhHeG9sOVpmcGQ1d2ZVVzBMRnF2bUF6L25KK0ZaMzIKbnlJeHlh
  VGlwekx4Mi9pOVpRTzlHTExFZUVNYmJIaWR6V1RQbkJvUWVvdFFnUEdvdjh2WnRPOWRNMTBxR0ww
  cgorWW9OVFZxbWEwTUJId1JPY2pzYnBreCs5MTcrZVdma3ovakttRU8zYVFLQmdRRFY3TVZ2REU5
  dUc4MWkxcHBoClFyYm9naXNIQ05xUHJsdU9qR2VibnJJRTl4aitnaVVreTk3MmZ1Zmx4NndseE5z
  OEtlWG1ObnJKYkNWb2MzREUKOG45QVZwRTVEcmdXYSthN242c1ZteWhBaHM0UG83N01HYWdhUWVF
  eERjZTQ5SGxHUmk1ZUNJaktSMDJ0L3lqUwp0L3VqaXdoaWhLVEdtb0RGTzd1Z1IzdGg5UUtCZ1FE
  SkY4Qk1TbVloZDZXR1d2dUtNMHVrOStUeW8waFZWMytGCjNqSlJqUFZpb3BZM0FldEZCVFh0T0hk
  am1ONm5PYlowdCtzZXZmMmFnWnFrdU80YnpsMlNOcElKK2ZTNmFVbEwKRW5aK3hzNmQ1T25CNllU
  SHZ2SVJZZEhuekdHaTBxZXFxMno0eU9OMEpyN2N3Q2lkalhValB4RDNxQlRwYktNQgppZ2NiV1Z4
  TEpRS0JnUUNIQjQvTHUzSjdwdkxxVzFsUTRRS0JHb0M4VFB0Z1RBY2dvRUZadWo3VjRYNldUMkhR
  CnF4ck9ibVpENU5nbGN1K0xOMHNWRi9oRElZOHZNZ2JSV2R1MnFhMjYzUzZYZ0g1QW1kVXNxeVlx
  TEt6dXRFWGYKb0tZNkJMRjIvQ0svL1JoN29ocnNZZWl0L1hucnhTNW9hNWRic0l1WFcvQ0NKODMy
  TVBFS2gzUTY3UUtCZ0h4cAo4SFNDOTBzdmZqNXczZjIwSE5IMCtUWlJaWGcvaVV0bW5KVXQ4OGZS
  dGNSVXNKM2tTbWY1TG94MVVSUC9OZTVpCnQ5b3VTOUFpN1cyS2FPN1ZMN2s5Zi84aUlaS1BmMlF1
  Q1JnSW9sNjMrUlFiQ1NhWDhhWmxjZnZLeklGemVYNnoKVHRsaFdMQk5KSHJwZkhkMXhJcEpBNU5s
  NzRJM3oyWXRZcFkrSkVidEFvR0FIc1RDRWJYdkdNTlJjVFU1MnVCMwpJbXNYWEdNZWZtVGVIbkRS
  OUJNaGwySm8zblhyVmNLeG9ZaEF1bVZMZ3Rvd2RyK0FZZGV1aWprTkhjdDExOXluCmZnYkdqQXpK
  ZFBJbXV1QURpQ3p4blNzNkhXOEtFZDlwZzFabU1aRzRMOGRRQnN1dGZqcjJ6SC9nWkljQTJLTTYK
  dTRnY2VtbzVwd2hzSXpBVFpuaU9EZ1k9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
